"""Initial migration with products JSON

Revision ID: 9b2f4f3133cb
Revises: 
Create Date: 2025-12-04 19:21:48.579276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9b2f4f3133cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tasting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('store_name', sa.String(length=150), nullable=False),
    sa.Column('products', sqlite.JSON(), nullable=True),
    sa.Column('bottles_to_sell', sa.Integer(), nullable=True),
    sa.Column('bottles_sold', sa.Integer(), nullable=True),
    sa.Column('bottles_left', sa.Integer(), nullable=True),
    sa.Column('total_bottles', sa.Integer(), nullable=True),
    sa.Column('poured_to_sold_percent', sa.Float(), nullable=True),
    sa.Column('tastings_poured', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasting')
    op.drop_table('user')
    # ### end Alembic commands ###
